### PR TITLE
feat: Added after movie and Anwesha name

### LINKED ISSUE #11: Add aftermovie in the app

### PR DESCRIPTION
**Pull request by debarghya472**
Screenshot_20191211-194411_Anwesha2k20

fixes: #11

### CODE REVIEW

**Review by s-ayush2903 — APPROVED** [review]

**Comment by somenath1435** [comment]
@debarghya472 write fixes #issue_number in PR description. When PR is merged, issue will autometically be closed

**Comment by atm1504** [comment]
@debarghya472 the code part is ok, please edit your comment and write the things mentioned by @somenath1435 .

**Comment by debarghya472** [comment]
issue number added. please review it.

**Comment by atm1504** [comment]
@debarghya472 not in the pr title. Add it in the comment where u have added the picture. 
Consider the following example
``` fixes: #11```

**Review by atm1504 — APPROVED** [review]

**Pull request merged**
