### PR TITLE
feat: Modify Registration Page and Developer's Page

### PR DESCRIPTION
**Pull request by Kavya-24**
Updated Developer's Page, Fixed Registration Page and disabled Call Function

### CODE REVIEW

**Comment by Kavya-24** [comment]
@atm1504  @somenath1435  Please review the changes made.

**Comment by atm1504** [comment]
@Kavya-24 kripiya karke ek screenshot attach kar dijiye  🥺

**Comment by Kavya-24** [comment]
WhatsApp Image 2020-01-07 at 17 55 18
WhatsApp Image 2020-01-07 at 17 55 06

**Comment by Kavya-24** [comment]
Please review.

**Review by atm1504 — APPROVED** [review]

**Pull request merged**
